version: '3.6'

services:
    mariadb:
        image: mariadb:inc
        container_name: mariadb
        build:
            context: ./requirements/mariadb
        volumes:
            - mariadb-data-volume:/var/lib/mysql
        networks:
            - inception-docker-network
        restart: on-failure
        env_file:
            - .env

    wordpress:
        container_name: wordpress
        image: wordpress:inc
        build:
            context: ./requirements/wordpress
        volumes:
            - wordpress-files-volume:/var/www/wordpress
        networks:
            - inception-docker-network
        depends_on:
            - mariadb
            - redis
        restart: on-failure
        environment:
            MYSQL_HOST: mariadb
            WORDPRESS_URL: https://zel-bouz.42.fr
            WP_REDIS_HOST: redis
            WP_REDIS_PORT: 6379
        env_file:
            - .env

    nginx:
        container_name: nginx
        image: nginx:inc
        build:
            context: ./requirements/nginx
        volumes:
            - wordpress-files-volume:/var/www/wordpress
            - adminer-files-volume:/var/www/adminer
        networks:
            - inception-docker-network
        ports:
            - 443:443
        restart: always
        depends_on:
            - wordpress
            - adminer

    redis:
        image: redis:inc
        container_name: redis
        build:
            context: ./requirements/bonus/redis
        networks:
            - inception-docker-network
        restart: on-failure

    ftp:
        image: ftp:inc
        container_name: ftp
        build:
            context: ./requirements/bonus/ftp
        networks:
            - inception-docker-network
        ports:
            - 20:20
            - 21:21
            - 30000-30010:30000-30010
        depends_on:
            - wordpress
        volumes:
            - wordpress-files-volume:/srv/ftp/wordpress
        restart: on-failure
        env_file:
            - .env

    adminer:
        container_name: adminer
        image: adminer:inc
        build:
            context: ./requirements/bonus/adminer
        networks:
            - inception-docker-network
        depends_on:
            - mariadb
        volumes:
            - adminer-files-volume:/var/www/adminer
        restart: on-failure

networks:
    inception-docker-network:
        name: inception-docker-network
        driver: bridge

volumes:
    wordpress-files-volume:
        name: wordpress-files-volume
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ${HOME}/data/wordpress

    mariadb-data-volume:
        name: mariadb-data-volume
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ${HOME}/data/mariadb

    adminer-files-volume:
        name: adminer-files-volume
        driver: local
        driver_opts:
            o: bind
            type: none
            device: ${HOME}/data/adminer
