
services:
    mariadb:
        image: mariadb:inc
        container_name: mariadb
        build:
            context: ./requirements/mariadb
        volumes:
            - mariadb-data-volume:/var/lib/mysql
        networks:
            - inception-docker-network
        restart: on-failure
        env_file:
            - .env

    wordpress:
        container_name: wordpress
        image: wordpress:inc
        build:
            context: ./requirements/wordpress
        volumes:
            - wordpress-files-volume:/var/www/html
        networks:
            - inception-docker-network
        restart: on-failure
        environment:
            MYSQL_HOST: mariadb
            WORDPRESS_URL: https://zel-bouz.42.fr
            WP_REDIS_HOST: redis
            WP_REDIS_PORT: 6379
        env_file:
            - .env

    nginx:
        container_name: nginx
        image: nginx:inc
        build:
            context: ./requirements/nginx
        volumes:
            - wordpress-files-volume:/var/www/html
        networks:
            - inception-docker-network
        ports:
            - 443:443
        restart: always
        depends_on:
            - wordpress

    app:
        container_name: app
        image: app:inc
        build:
            context: ./requirements/bonus/app
        networks:
            - inception-docker-network

    redis:
        image: redis:inc
        container_name: redis
        build:
            context: ./requirements/bonus/redis
        networks:
            - inception-docker-network
        restart: on-failure

    ftp:
        image: ftp:inc
        container_name: ftp
        build:
            context: ./requirements/bonus/ftp
        networks:
            - inception-docker-network
        ports:
            - 21:21

        depends_on:
            - wordpress
        volumes:
            - wordpress-files-volume:/home/ftp/
        restart: on-failure
        env_file:
            - .env

    adminer:
        container_name: adminer
        image: adminer:inc
        build:
            context: ./requirements/bonus/adminer
        networks:
            - inception-docker-network
        depends_on:
            - mariadb
        restart: on-failure

networks:
    inception-docker-network:
        name: inception-docker-network
        driver: bridge

volumes:
    wordpress-files-volume:
        name: wordpress-files-volume
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /home/zakariaelbouzkri/data/wordpress

    mariadb-data-volume:
        name: mariadb-data-volume
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /home/zel-bouz/data/mariadb

