version: '3'

services:
    mariadb:
        container_name: mariadb
        image: mariadb:inc
        build:
            context: ./services/mariadb
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - inception_net
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}


    wordpress:
        container_name: wordpress
        image: wordpress:inc
        build:
            context: ./services/wordpress
        volumes:
            - wordpress_files:/var/www/wordpress
        networks:
            - inception_net
        depends_on:
            - mariadb
            - redis
        restart: on-failure
        environment:
            MYSQL_HOST: mariadb
            WORDPRESS_URL: http://localhost
            WP_SITE_TITLE: Inception
            WP_REDIS_HOST: redis
            WP_REDIS_PORT: 6379
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            WP_ADMIN_USER: ${WP_ADMIN_USER}
            WP_ADMIN_PASS: ${WP_ADMIN_PASS}
            WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
            WP_USER_USERNAME: ${WP_USER_USERNAME}
            WP_USER_EMAIL: ${WP_USER_EMAIL}
            WP_USER_ROLE: ${WP_USER_ROLE}
            WP_USER_PASS: ${WP_USER_PASS}

    nginx:
        container_name: nginx
        image: nginx:inc
        build:
            context: ./services/nginx
        volumes:
            - wordpress_files:/var/www/wordpress/
            - adminer_files:/var/www/adminer
        networks:
            - inception_net
        ports:
            - "443:443"
            - "80:80"
            - "8080:8080"
        restart: always
        depends_on:
            - wordpress

    redis:
        container_name: redis
        image: redis:inc
        build:
            context: ./services/redis
        networks:
            - inception_net
        restart: on-failure
    
    ftp:
        container_name: ftp
        image: ftp:inc
        build:
            context: ./services/ftp_server
        networks:
            - inception_net
        ports:
            - 20:20
            - 21:21
            - 30000-30010:30000-30010
        depends_on:
            - wordpress
        volumes:
            - wordpress_files:/srv/ftp/wordpress/
        environment:
            FTP_USER: ftp_user
            FTP_PASSWORD: ftp_pass
    adminer:
        container_name: adminer
        image: adminer:inc
        build:
            context: ./services/adminer
        networks:
            - inception_net
        depends_on:
            - mariadb
        volumes:
            - adminer_files:/var/www/adminer

volumes:
    wordpress_files:
    mariadb_data:
    adminer_files:

networks:
    inception_net: