version: '3'

services:
  db:
    container_name: mariadb
    build: ./services/mariadb/
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql/

    networks:
      - inception
    restart: on-failure

  proxy:
    container_name: nginx
    build: ./services/nginx/
    ports:
      - "443:443"
      - "80:80"
    restart: always
    networks:
      - inception
    depends_on:
      - db
      - app
    volumes:
      - wordpress_files:/var/www/html/

  app:
    container_name: wordpress
    build: ./services/wordpress
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=db
      - WORDPRESS_URL=http://localhost
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASS=${WP_ADMIN_PASS}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_SITE_TITLE="inception"
      - WP_REDIS_HOST="redis"
      - WP_REDIS_PORT="6379"
    networks:
      - inception
    volumes:
      - wordpress_files:/var/www/html/
    depends_on:
      - db

  redis:
    build: ./services/redis
    networks:
      - inception



volumes:
  mariadb_data:
  wordpress_files:


networks:
  inception:

