version: '3'

services:
  db:
    container_name: mariadb
    build: ./services/mariadb/
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql/

    networks:
      - inception
    restart: on-failure

  
  proxy:
    container_name: nginx
    build: ./services/nginx/
    ports:
      - "443:443"
    restart: always
    networks:
      - inception
    depends_on:
      - db

volumes:
  mariadb_data:


networks:
  inception:

